# Generated by Django 5.0.1 on 2024-01-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcard", "0002_flashcarddesafio_desafio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="desafio",
            name="Flashcard",
        ),
        migrations.AddField(
            model_name="desafio",
            name="flashcard",
            field=models.ManyToManyField(to="flashcard.flashcarddesafio"),
        ),
    ]
