# Generated by Django 5.0.1 on 2024-01-21 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flashcard", "0003_remove_desafio_flashcard_desafio_flashcard"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flashcarddesafio",
            old_name="Flashcard",
            new_name="flashcard",
        ),
    ]
